#!/bin/bash

PHP=$(dpkg-query -W -f='$(Status)' php7.3 2>/dev/null | grep -c "ok installed")

if [ $PHP -eq 0 ];  then
	echo "Paigaldame php ja vajalikud lisad"
	apt install php7.3 libapache2-mod-php7.3 php7.3-mysql
	echo "PHP on paigaldatud"
elif [ $PHP -eq 1 ]; then
	echo "PHP on juba paigaldatud"
	which php
fi
