#!/bin/bash

#Algne kogusumma
summa=0

#Arvutus - 1-10, kui arv on paaris, liida kogusummale
for (( arv=1; arv<11; arv++ ))
do
	jaak=$(($arv % 2))
	if [ $jaak -eq 0 ]; then
		summa=$(($summa + $arv))
		echo $summa
	fi
done

#Väljastus kasutajale
echo "Arvude vahemiks 1 kuni 10 (kaasaarvatud) paarisarvude summa on: $summa"

