#!/bin/bash

#Küsime kasutajalt sisendit
read -p "Sisesta suvaline täisarv: " arv

summa=0

#Algoritm sisestatud numbrit summa arvutamiseks
while [ $arv -ne 0 ]
do
	jaak=$(($arv % 10))
	summa=$(($summa + $jaak))
	arv=$(($arv / 10))
done
echo "$summa"
