#!/bin/bash

#Küsime kasutajalt sisendit
read -p "Sisesta suvaline arv: " arv

#Kontrollime, kas arv on algarv või mitte
if [ $arv -eq 0 -o $arv -eq 1 ]; then
	echo "$arv - tegemist ei ole algarvuga!"
else
	jagaja=2
	jaak=$(($arv % $jagaja))
	while [ $jaak -ne 0 ]
	do
		jagaja=$(($jagaja + 1))
		jaak=$(($arv % $jagaja))
	done
	if [ $arv -eq $jagaja ]; then
		echo "$arv - tegemist on algarvuga!"
	else
		echo "$arv - tegemist ei ole algarvuga!"
	fi
fi
