#!/bin/bash

#Kontrollime, kas kasutaja on sisestanud tahetud failid korrektselt

if [ $# -ne 2 ]; then
	echo "Kasutusjuhend: $0 kasutajatefailinimi paroolidefailinimi"
else
	kasutajad_fail=$1
	paroolide_fail=$2

	#Kontroll, kas sisestatud failid on ikkagist failid ja kas nad on loetavad

	if [ -f $kasutajad_fail -a -r $kasutajad_fail -a -f $paroolide_fail -a -r $paroolide_fail ]; then
		echo "Failid on korras."

		#Sisestame parameetrid failidest

		paste -d' ' "$kasutajad_fail" "$paroolide_fail" | while read -r kasutajanimi parool; do

		#Loome kasutajad, kui parameetrid on loetavad

		if [ -n "$kasutajanimi" ] && [ -n "$parool" ]; then
			useradd "$kasutajanimi" -m -s /bin/bash
			kasu_tulemus_nimi=$?
			echo "$kasutajanimi:$parool" | chpasswd
			kasu_tulemus_parool=$?

			#Kontrollime, kas  kasutaja loomine oli edukas ning prindime vastavalt tulemuse

			if [ $kasu_tulemus_nimi -eq 0 -a $kasu_tulemus_parool -eq 0 ]; then
				echo "Kasutaja nimega $kasutajanimi ja parooliga $parool on lisatud süsteemi"
				cat /etc/passwd | grep $kasutajanimi
				ls -la /home/$kasutajanimi
			else
				if [ $kasu_tulemus_nimi -eq 0 ]; then
					echo "Probleem parooliga."
				elif [ $kasu_tulemus_parool -eq 0 ]; then
					echo "Probleem nimega."
				else
					echo "Probleem parooliga ja nimega."
				fi
			fi
		fi
	done

	#Anname veateate juhul, kui failide lugemisega on probleeme.

	else
		if [ -f $kasutajad_fail -a -r $kasutajad_fail ]; then
			echo "Probleem failiga $paroolide_fail"
		elif [ -f $paroolide_fail -a -r $paroolide_fail ]; then
			echo "Probleem failiga $kasutajad_fail"
		else
			echo "Probleem failidega $kasutajad_fail ja $paroolide_fail"
		fi

	fi
fi


