#!/bin/bash

if [ $# -ne 2 ]; then
	echo "Kasutusjuhend: $0 kasutajatefailinimi paroolidefailinimi"
else
	kasutajad_fail=$1
	paroolide_fail=$2

	if [ -f $kasutajad_fail -a -r $kasutajad_fail -a -f $paroolide_fail -a -r $paroolide_fail ]; then
		echo "Failid on korras."
		paste -d' ' "$kasutajad_fail" "$paroolide_fail" | while read -r kasutajanimi parool; do

		if [ -n "$kasutajanimi" ] && [ -n "$parool" ]; then
			useradd "$kasutajanimi" -m -s /bin/bash
			kasu_tulemus_nimi=$?
			echo "$kasutajanimi:$parool" | chpasswd
			kasu_tulemus_parool=$?

			if [ $kasu_tulemus_nimi -eq 0 -a $kasu_tulemus_parool -eq 0 ]; then
				echo "Kasutaja nimega $kasutajanimi ja parooliga $parool on lisatud süsteemi"
				cat /etc/passwd | grep $kasutajanimi
				ls -la /home/$kasutajanimi
			else
				if [ $kasu_tulemus_nimi -eq 0 ]; then
					echo "Probleem parooliga."
				elif [ $kasu_tulemus_parool -eq 0 ]; then
					echo "Probleem nimega."
				else
					echo "Probleem parooliga ja nimega."
				fi
			fi
		fi
	done
	fi
fi


