#!/bin/bash
# Skript bussiekskursioonide korraldajale
# Küsib kasutajalt mitu reisijat  ja kohta on ning muudab need muutujateks
read -p "Mitu reisijat on grupis?: " reisijad
read -p "Mitu kohta on bussis?: " kohad

# Arvutused, mitu täis bussi ning mitu jäi maha
tais_bussid=$((reisijad / kohad))
mahajaanud=$((reisijad % kohad))

#Arvutus busside liitmiseks
if test $mahajaanud -gt 0
then
	tais_bussid=$(($tais_bussid + 1))
fi

#Väljastame palju täis busse siis lõpuks vaja läheb
echo "Kokku on vaja $tais_bussid taisbussi."
