#!/bin/bash

#Kontrollime, kas skripti käivitab root kasutaja või mitte
kaivitatav_kasutaja=$(whoami)

if [ $kaivitatav_kasutaja = "root" ]; then

	#Kontrollime, kas skripti jooksutati õigesti

	if [ $# -ne 1 ]; then
		echo "Kasutusjuhend: $0 kasutajad"
	else
		kasutajad=$1

		#Loome kasutajad samal ajal kontrollides, kas antud failid on loetavad

		if [ -f $kasutajad -a -r $kasutajad ]; then
			echo "Failid on korras"
			for rida in $(paste -d: $kasutajad $paroolid)
			do
				kasutajanimi=$(echo "$rida")

				#Jooksutame eelnevat skripti ning loome neile suvaliselt genereeritud parooli

				sh lisakasutaja $kasutajanimi
				parool=$(pwgen -s 8 -1)
				echo "$kasutajanimi:$parool" | chpasswd

				#Lisame parooli ka faili, et hiljem teada saada, kes millist parooli omab

				echo "$kasutajanimi - $parool" >> loodud_kasutajad_paroolidega
			done
		else
			echo "Probleem failiga $failinimi"
		fi
	fi
else
	echo "Sul ei ole õigust antud skripti jooksutada"
fi
