#!/bin/bash

#Võtame kasutajanime
kasutajanimi=$(whoami)

#Hetke kellaaja täistund
taistund=$(date +%H)

#Kontrollime, mis kell on
if [ $taistund -ge 6 -a $taistund -lt 12 ]; then
	echo "Tere hommikust, $kasutajanimi!"
elif [ $taistund -ge 12 -a $taistund -lt 18 ]; then
	echo "Tere päevast, $kasutajanimi !"
elif [ $taistund -ge 18 -a $taistund -lt 22 ]; then
	echo "Tere õhtust, $kasutajanimi !"
elif [ $taistund -ge 22 -a $taistund -lt 24 ]; then
	echo "Head ööd, $kasutajanimi !"
elif [ $taistund -ge 22 -a $taistund -le 24 ] || [ $taistund -ge 0 -a $taistund -lt 6 ]; then
        echo "Head ööd, $kasutajanimi !"

else
	echo "Vale sisend!"
fi

