#!/bin/bash

#Küsime kasutajalt aega
read -p "Sisesta aja vaartus: \c" aeg

#Kontrollime, mis kell on
if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
	echo "Tere hommikust!"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
	echo "Tere päevast!"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
	echo "Tere õhtust!"
elif [ $aeg - ge 22 -a $aeg -lt 24 ]; then
	echo "Head ööd!"
else
	echo "Vale sisend!"
fi

